// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TagExplorer.Data;

#nullable disable

namespace TagExplorer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250220200438_AddedFolderTableClasses")]
    partial class AddedFolderTableClasses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TagExplorer.Data.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("varchar(7)");

                    b.Property<bool>("IsSystemColor")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("TagExplorer.Data.FolderBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FolderType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AutoAssignmentRules");

                    b.HasDiscriminator<string>("FolderType").HasValue("FolderBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TagExplorer.Data.IconFavourite", b =>
                {
                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.HasKey("IconName");

                    b.ToTable("IconFavourites");
                });

            modelBuilder.Entity("TagExplorer.Data.TagDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("Aliases")
                        .HasColumnType("text[]");

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsSystemTag")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ParentId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TagExplorer.Data.BaseFolder", b =>
                {
                    b.HasBaseType("TagExplorer.Data.FolderBase");

                    b.HasDiscriminator().HasValue("BaseFolder");
                });

            modelBuilder.Entity("TagExplorer.Data.Folder", b =>
                {
                    b.HasBaseType("TagExplorer.Data.FolderBase");

                    b.Property<int?>("FolderId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentFolderId")
                        .HasColumnType("integer");

                    b.HasIndex("FolderId");

                    b.HasIndex("ParentFolderId");

                    b.HasDiscriminator().HasValue("Folder");
                });

            modelBuilder.Entity("TagExplorer.Data.TagDTO", b =>
                {
                    b.HasOne("TagExplorer.Data.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TagExplorer.Data.TagDTO", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Color");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TagExplorer.Data.Folder", b =>
                {
                    b.HasOne("TagExplorer.Data.Folder", null)
                        .WithMany("Folders")
                        .HasForeignKey("FolderId");

                    b.HasOne("TagExplorer.Data.FolderBase", "ParentFolder")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("TagExplorer.Data.FolderBase", b =>
                {
                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("TagExplorer.Data.TagDTO", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("TagExplorer.Data.Folder", b =>
                {
                    b.Navigation("Folders");
                });
#pragma warning restore 612, 618
        }
    }
}
